"""Geographical and marketplace lookup mappings and utility helpers."""

# Country name mapping to ISO 2-letter codes for Google Trends (SerpApi)
COUNTRY_TO_GEO = {
    "afghanistan": "AF",
    "albania": "AL",
    "algeria": "DZ",
    "andorra": "AD",
    "angola": "AO",
    "antigua and barbuda": "AG",
    "argentina": "AR",
    "armenia": "AM",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "bahamas": "BS",
    "bahrain": "BH",
    "bangladesh": "BD",
    "barbados": "BB",
    "belarus": "BY",
    "belgium": "BE",
    "belize": "BZ",
    "benin": "BJ",
    "bhutan": "BT",
    "bolivia": "BO",
    "bosnia and herzegovina": "BA",
    "botswana": "BW",
    "brazil": "BR",
    "brunei": "BN",
    "bulgaria": "BG",
    "burkina faso": "BF",
    "burundi": "BI",
    "cabo verde": "CV",
    "cambodia": "KH",
    "cameroon": "CM",
    "canada": "CA",
    "central african republic": "CF",
    "chad": "TD",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "comoros": "KM",
    "congo": "CG",
    "costa rica": "CR",
    "croatia": "HR",
    "cuba": "CU",
    "cyprus": "CY",
    "czech republic": "CZ",
    "czechia": "CZ",
    "denmark": "DK",
    "djibouti": "DJ",
    "dominica": "DM",
    "dominican republic": "DO",
    "ecuador": "EC",
    "egypt": "EG",
    "el salvador": "SV",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "estonia": "EE",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "ethiopia": "ET",
    "fiji": "FJ",
    "finland": "FI",
    "france": "FR",
    "gabon": "GA",
    "gambia": "GM",
    "georgia": "GE",
    "germany": "DE",
    "ghana": "GH",
    "greece": "GR",
    "grenada": "GD",
    "guatemala": "GT",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "haiti": "HT",
    "honduras": "HN",
    "hungary": "HU",
    "iceland": "IS",
    "india": "IN",
    "indonesia": "ID",
    "iran": "IR",
    "iraq": "IQ",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "jamaica": "JM",
    "japan": "JP",
    "jordan": "JO",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "kiribati": "KI",
    "north korea": "KP",
    "south korea": "KR",
    "korea": "KR",
    "kuwait": "KW",
    "kyrgyzstan": "KG",
    "laos": "LA",
    "latvia": "LV",
    "lebanon": "LB",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "liechtenstein": "LI",
    "lithuania": "LT",
    "luxembourg": "LU",
    "madagascar": "MG",
    "malawi": "MW",
    "malaysia": "MY",
    "maldives": "MV",
    "mali": "ML",
    "malta": "MT",
    "marshall islands": "MH",
    "mauritania": "MR",
    "mauritius": "MU",
    "mexico": "MX",
    "micronesia": "FM",
    "moldova": "MD",
    "monaco": "MC",
    "mongolia": "MN",
    "montenegro": "ME",
    "morocco": "MA",
    "mozambique": "MZ",
    "myanmar": "MM",
    "burma": "MM",
    "namibia": "NA",
    "nauru": "NR",
    "nepal": "NP",
    "netherlands": "NL",
    "new zealand": "NZ",
    "nicaragua": "NI",
    "niger": "NE",
    "nigeria": "NG",
    "north macedonia": "MK",
    "norway": "NO",
    "oman": "OM",
    "pakistan": "PK",
    "palau": "PW",
    "panama": "PA",
    "papua new guinea": "PG",
    "paraguay": "PY",
    "peru": "PE",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "qatar": "QA",
    "romania": "RO",
    "russia": "RU",
    "rwanda": "RW",
    "saint kitts and nevis": "KN",
    "saint lucia": "LC",
    "saint vincent and the grenadines": "VC",
    "samoa": "WS",
    "san marino": "SM",
    "sao tome and principe": "ST",
    "saudi arabia": "SA",
    "senegal": "SN",
    "serbia": "RS",
    "seychelles": "SC",
    "sierra leone": "SL",
    "singapore": "SG",
    "slovakia": "SK",
    "slovenia": "SI",
    "solomon islands": "SB",
    "somalia": "SO",
    "south africa": "ZA",
    "south sudan": "SS",
    "spain": "ES",
    "sri lanka": "LK",
    "sudan": "SD",
    "suriname": "SR",
    "sweden": "SE",
    "switzerland": "CH",
    "syria": "SY",
    "taiwan": "TW",
    "tajikistan": "TJ",
    "tanzania": "TZ",
    "thailand": "TH",
    "timor-leste": "TL",
    "togo": "TG",
    "tonga": "TO",
    "trinidad and tobago": "TT",
    "tunisia": "TN",
    "turkey": "TR",
    "turkiye": "TR",
    "turkmenistan": "TM",
    "tuvalu": "TV",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "uae": "AE",
    "united kingdom": "GB",
    "uk": "GB",
    "great britain": "GB",
    "united states": "US",
    "united states of america": "US",
    "us": "US",
    "usa": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "vanuatu": "VU",
    "venezuela": "VE",
    "vietnam": "VN",
    "yemen": "YE",
    "zambia": "ZM",
    "zimbabwe": "ZW"
}

# Fast check set of all valid ISO codes
VALID_CODES = set(COUNTRY_TO_GEO.values())

# Amazon marketplace domains lookup table
AMAZON_DOMAINS = {
    "united states": "com",
    "us": "com",
    "usa": "com",
    "india": "in",
    "in": "in",
    "united kingdom": "co.uk",
    "uk": "co.uk",
    "gb": "co.uk",
    "great britain": "co.uk",
    "canada": "ca",
    "ca": "ca",
    "germany": "de",
    "de": "de",
    "australia": "com.au",
    "au": "com.au",
    "japan": "co.jp",
    "jp": "co.jp",
    "united arab emirates": "ae",
    "uae": "ae",
    "ae": "ae",
    "france": "fr",
    "fr": "fr",
    "italy": "it",
    "it": "it",
    "spain": "es",
    "es": "es",
    "mexico": "com.mx",
    "mx": "com.mx",
    "brazil": "com.br",
    "br": "com.br",
    "netherlands": "nl",
    "nl": "nl",
    "singapore": "sg",
    "sg": "sg",
    "saudi arabia": "sa",
    "sa": "sa",
    "sweden": "se",
    "se": "se",
    "poland": "pl",
    "pl": "pl",
    "turkey": "com.tr",
    "tr": "com.tr",
    "belgium": "com.be",
    "be": "com.be",
    "egypt": "eg",
    "eg": "eg",
    "south africa": "co.za",
    "za": "co.za"
}

def get_country_geo(country_name: str) -> str | None:
    """
    Returns the 2-letter ISO 3166-1 code for a given country name or abbreviation.
    If the input is already a valid 2-letter code, returns it directly in uppercase.
    """
    if not country_name:
        return None
        
    cleaned = country_name.strip().upper()
    if len(cleaned) == 2 and cleaned in VALID_CODES:
        return cleaned
        
    return COUNTRY_TO_GEO.get(country_name.strip().lower())

def get_amazon_domain(country_name: str) -> str:
    """
    Resolves the Amazon marketplace domain (e.g. 'com', 'in', 'co.uk') for a given country.
    Defaults to 'com' if the country is not mapped or empty.
    """
    if not country_name:
        return "com"
        
    cleaned = country_name.strip().lower()
    return AMAZON_DOMAINS.get(cleaned, "com")
